#!/usr/bin/env bash

render_chrony_regional_sources() {
  local region="${TIME_REGION:-global}"
  cat <<'EOF'
# Generated by roko-edge-tools. Keep at least two selectable sources.
# ntp01.roko.network is an optional bootstrap/consistency source, not a
# Stratum 1/2 authority.
server ntp01.roko.network iburst minpoll 6 maxpoll 10
EOF
  case "$region" in
    americas)
      cat <<'EOF'
server time-a-g.nist.gov iburst minpoll 6 maxpoll 10
server time-d-b.nist.gov iburst minpoll 6 maxpoll 10
pool north-america.pool.ntp.org iburst maxsources 2
EOF
      ;;
    europe)
      cat <<'EOF'
server ptbtime1.ptb.de iburst minpoll 6 maxpoll 10
server ptbtime4.ptb.de iburst minpoll 6 maxpoll 10
pool europe.pool.ntp.org iburst maxsources 2
EOF
      ;;
    asia)
      cat <<'EOF'
server ntp.nict.jp iburst minpoll 6 maxpoll 10
pool asia.pool.ntp.org iburst maxsources 3
EOF
      ;;
    oceania)
      cat <<'EOF'
server ntp.nict.jp iburst minpoll 6 maxpoll 10
pool oceania.pool.ntp.org iburst maxsources 3
EOF
      ;;
    africa)
      cat <<'EOF'
pool africa.pool.ntp.org iburst maxsources 3
pool europe.pool.ntp.org iburst maxsources 2
EOF
      ;;
    global)
      cat <<'EOF'
server time-a-g.nist.gov iburst minpoll 6 maxpoll 10
server ptbtime4.ptb.de iburst minpoll 6 maxpoll 10
server ntp.nict.jp iburst minpoll 6 maxpoll 10
pool pool.ntp.org iburst maxsources 2
EOF
      ;;
    *) fail "TIME_REGION must be global, americas, europe, asia, oceania, or africa." ;;
  esac
  cat <<'EOF'
minsources 2
EOF
}
